title: Arshia Kavan
description: Undergraduate Student in Physics, Astronomy, and Mathematics at the University of Arizona.
tagline: "Also published as Arshia Akhtarkavan"
url: https://aakavan.com
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
