title: Arshia Kavan
description: "Also published as Arshia Akhtarkavan · Undergraduate in Physics, Astronomy, and Mathematics at the University of Arizona"
url: https://aakavan.com
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  math_engine: mathjax
